name:                primes
version:             0.1.0.0
github:              "leetschau/primes"
license:             BSD3
author:              "Leo"
maintainer:          "leetschau@gmail.com"
copyright:           "2019 Leo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Study

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/leetschau/primes#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  primes-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - primes

tests:
  primes-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - primes
    - QuickCheck
